-- ====================================================================
-- SERVER PERFORMANCE MONITORING SYSTEM
-- Oracle PL/SQL Implementation
-- ====================================================================

-- **TAKE SCREENSHOT 1: Before starting - Clean workspace**

-- ====================================================================
-- STEP 1: CREATE TABLES FOR PERFORMANCE MONITORING
-- ====================================================================

-- Drop existing tables if they exist (cleanup)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE server_alerts';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE performance_metrics';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Create performance metrics table
CREATE TABLE performance_metrics (
    metric_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_name VARCHAR2(100) NOT NULL,
    metric_type VARCHAR2(50) NOT NULL, -- CPU, MEMORY, DISK, NETWORK
    metric_value NUMBER(10,2) NOT NULL,
    threshold_limit NUMBER(10,2) DEFAULT 80,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'NORMAL' -- NORMAL, WARNING, CRITICAL
);

-- Create alerts table
CREATE TABLE server_alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_name VARCHAR2(100) NOT NULL,
    metric_type VARCHAR2(50) NOT NULL,
    metric_value NUMBER(10,2) NOT NULL,
    threshold_breached NUMBER(10,2) NOT NULL,
    alert_level VARCHAR2(20) NOT NULL, -- WARNING, CRITICAL
    alert_message VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    acknowledged CHAR(1) DEFAULT 'N'
);

-- **TAKE SCREENSHOT 2: After creating tables - Show table structures**
-- Run: DESC performance_metrics; and DESC server_alerts;

-- ====================================================================
-- STEP 2: CREATE PROCEDURES FOR LOGGING METRICS
-- ====================================================================

-- Procedure to log server metrics
CREATE OR REPLACE PROCEDURE log_server_metrics (
    p_server_name IN VARCHAR2,
    p_metric_type IN VARCHAR2,
    p_metric_value IN NUMBER,
    p_threshold IN NUMBER DEFAULT 80
) IS
    v_status VARCHAR2(20);
BEGIN
    -- Determine status based on threshold
    IF p_metric_value >= p_threshold THEN
        v_status := 'CRITICAL';
    ELSIF p_metric_value >= (p_threshold * 0.8) THEN
        v_status := 'WARNING';
    ELSE
        v_status := 'NORMAL';
    END IF;
    
    -- Insert the metric
    INSERT INTO performance_metrics (
        server_name, metric_type, metric_value, threshold_limit, status
    ) VALUES (
        p_server_name, p_metric_type, p_metric_value, p_threshold, v_status
    );
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Metric logged: ' || p_server_name || ' - ' || 
                        p_metric_type || ' = ' || p_metric_value || '%');
END log_server_metrics;
/

-- Procedure for bulk metrics logging
CREATE OR REPLACE PROCEDURE log_bulk_metrics (
    p_server_name IN VARCHAR2
) IS
BEGIN
    -- Simulate logging multiple metrics for a server
    log_server_metrics(p_server_name, 'CPU', ROUND(DBMS_RANDOM.VALUE(60, 95), 2), 80);
    log_server_metrics(p_server_name, 'MEMORY', ROUND(DBMS_RANDOM.VALUE(50, 90), 2), 85);
    log_server_metrics(p_server_name, 'DISK', ROUND(DBMS_RANDOM.VALUE(40, 95), 2), 90);
    log_server_metrics(p_server_name, 'NETWORK', ROUND(DBMS_RANDOM.VALUE(30, 80), 2), 75);
    
    DBMS_OUTPUT.PUT_LINE('Bulk metrics logged for server: ' || p_server_name);
END log_bulk_metrics;
/

-- **TAKE SCREENSHOT 3: After creating procedures - Show procedure creation success**

-- ====================================================================
-- STEP 3: CREATE TRIGGERS FOR THRESHOLD ALERTS
-- ====================================================================

-- Trigger to generate alerts when thresholds are breached
CREATE OR REPLACE TRIGGER trg_performance_alert
    AFTER INSERT ON performance_metrics
    FOR EACH ROW
WHEN (NEW.status IN ('WARNING', 'CRITICAL'))
DECLARE
    v_alert_message VARCHAR2(500);
    v_alert_level VARCHAR2(20);
BEGIN
    -- Determine alert level and message
    IF :NEW.status = 'CRITICAL' THEN
        v_alert_level := 'CRITICAL';
        v_alert_message := 'CRITICAL ALERT: Server ' || :NEW.server_name || 
                          ' ' || :NEW.metric_type || ' usage at ' || 
                          :NEW.metric_value || '% (Threshold: ' || 
                          :NEW.threshold_limit || '%)';
    ELSE
        v_alert_level := 'WARNING';
        v_alert_message := 'WARNING: Server ' || :NEW.server_name || 
                          ' ' || :NEW.metric_type || ' usage at ' || 
                          :NEW.metric_value || '% (Threshold: ' || 
                          :NEW.threshold_limit || '%)';
    END IF;
    
    -- Insert alert
    INSERT INTO server_alerts (
        server_name, metric_type, metric_value, 
        threshold_breached, alert_level, alert_message
    ) VALUES (
        :NEW.server_name, :NEW.metric_type, :NEW.metric_value,
        :NEW.threshold_limit, v_alert_level, v_alert_message
    );
    
    -- Output to console (simulating real-time alerting)
    DBMS_OUTPUT.PUT_LINE('🚨 ALERT GENERATED: ' || v_alert_message);
END;
/

-- **TAKE SCREENSHOT 4: After creating triggers - Show trigger creation**

-- ====================================================================
-- STEP 4: CREATE FUNCTIONS FOR HEALTH CHECKS
-- ====================================================================

-- Function to get server health status
CREATE OR REPLACE FUNCTION get_server_health_status (
    p_server_name IN VARCHAR2
) RETURN VARCHAR2 IS
    v_critical_count NUMBER;
    v_warning_count NUMBER;
    v_health_status VARCHAR2(20);
BEGIN
    -- Count recent critical and warning metrics (last 24 hours)
    SELECT 
        COUNT(CASE WHEN status = 'CRITICAL' THEN 1 END),
        COUNT(CASE WHEN status = 'WARNING' THEN 1 END)
    INTO v_critical_count, v_warning_count
    FROM performance_metrics 
    WHERE server_name = p_server_name 
    AND recorded_at >= SYSTIMESTAMP - INTERVAL '1' DAY;
    
    -- Determine overall health
    IF v_critical_count > 0 THEN
        v_health_status := 'CRITICAL';
    ELSIF v_warning_count > 2 THEN
        v_health_status := 'DEGRADED';
    ELSIF v_warning_count > 0 THEN
        v_health_status := 'WARNING';
    ELSE
        v_health_status := 'HEALTHY';
    END IF;
    
    RETURN v_health_status;
END get_server_health_status;
/

-- Function to calculate average metric value
CREATE OR REPLACE FUNCTION get_avg_metric_value (
    p_server_name IN VARCHAR2,
    p_metric_type IN VARCHAR2,
    p_hours IN NUMBER DEFAULT 24
) RETURN NUMBER IS
    v_avg_value NUMBER;
BEGIN
    SELECT NVL(AVG(metric_value), 0)
    INTO v_avg_value
    FROM performance_metrics
    WHERE server_name = p_server_name
    AND metric_type = p_metric_type
    AND recorded_at >= SYSTIMESTAMP - INTERVAL '1' DAY;
    
    RETURN ROUND(v_avg_value, 2);
END get_avg_metric_value;
/

-- **TAKE SCREENSHOT 5: After creating functions - Show function creation**

-- ====================================================================
-- STEP 5: INSERT TEST DATA
-- ====================================================================

-- Enable DBMS_OUTPUT to see messages
SET SERVEROUTPUT ON;

-- Insert sample performance data
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== LOGGING SAMPLE PERFORMANCE METRICS ===');
    
    -- Log metrics for multiple servers
    log_bulk_metrics('WEB-SERVER-01');
    log_bulk_metrics('DB-SERVER-01');
    log_bulk_metrics('APP-SERVER-01');
    
    -- Add some specific high-value metrics to trigger alerts
    log_server_metrics('WEB-SERVER-01', 'CPU', 92.5, 80);
    log_server_metrics('DB-SERVER-01', 'MEMORY', 94.8, 85);
    log_server_metrics('APP-SERVER-01', 'DISK', 96.2, 90);
    
    DBMS_OUTPUT.PUT_LINE('=== SAMPLE DATA INSERTION COMPLETED ===');
END;
/

-- **TAKE SCREENSHOT 6: After inserting test data - Show data insertion output**

-- ====================================================================
-- STEP 6: CURSORS FOR DAILY REPORTING
-- ====================================================================

-- Daily Performance Report using Cursors
CREATE OR REPLACE PROCEDURE generate_daily_report IS
    -- Cursor for server summary
    CURSOR c_server_summary IS
        SELECT 
            server_name,
            COUNT(*) as total_metrics,
            AVG(metric_value) as avg_performance,
            MAX(metric_value) as peak_usage,
            COUNT(CASE WHEN status = 'CRITICAL' THEN 1 END) as critical_count,
            COUNT(CASE WHEN status = 'WARNING' THEN 1 END) as warning_count
        FROM performance_metrics 
        WHERE recorded_at >= TRUNC(SYSDATE)
        GROUP BY server_name
        ORDER BY critical_count DESC, warning_count DESC;
    
    -- Cursor for top alerts
    CURSOR c_recent_alerts IS
        SELECT 
            server_name, 
            metric_type, 
            metric_value, 
            alert_level,
            alert_message,
            TO_CHAR(created_at, 'HH24:MI:SS') as alert_time
        FROM server_alerts 
        WHERE created_at >= TRUNC(SYSDATE)
        ORDER BY created_at DESC;
        
    v_health_status VARCHAR2(20);
BEGIN
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('📊 ====== DAILY PERFORMANCE REPORT ======');
    DBMS_OUTPUT.PUT_LINE('📅 Date: ' || TO_CHAR(SYSDATE, 'DD-MON-YYYY'));
    DBMS_OUTPUT.PUT_LINE('');
    
    -- Server Summary Report
    DBMS_OUTPUT.PUT_LINE('🖥️  SERVER PERFORMANCE SUMMARY:');
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 80, '-'));
    
    FOR rec IN c_server_summary LOOP
        v_health_status := get_server_health_status(rec.server_name);
        
        DBMS_OUTPUT.PUT_LINE('Server: ' || RPAD(rec.server_name, 20) || 
                           'Health: ' || RPAD(v_health_status, 10) ||
                           'Avg: ' || RPAD(TO_CHAR(rec.avg_performance, '999.99'), 8) ||
                           'Peak: ' || RPAD(TO_CHAR(rec.peak_usage, '999.99'), 8) ||
                           'Alerts: ' || (rec.critical_count + rec.warning_count));
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('🚨 RECENT ALERTS:');
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 80, '-'));
    
    -- Recent Alerts Report
    FOR alert_rec IN c_recent_alerts LOOP
        DBMS_OUTPUT.PUT_LINE('[' || alert_rec.alert_time || '] ' || 
                           alert_rec.alert_level || ': ' || 
                           alert_rec.server_name || ' - ' ||
                           alert_rec.alert_message);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('✅ Report Generation Completed');
END generate_daily_report;
/

-- **TAKE SCREENSHOT 7: After running reports - Show cursor/reporting output**
-- Run the daily report
BEGIN
    generate_daily_report;
END;
/

-- ====================================================================
-- STEP 7: HEALTH CHECK QUERIES
-- ====================================================================

-- Display current server health status
SELECT 
    DISTINCT server_name,
    get_server_health_status(server_name) as health_status,
    get_avg_metric_value(server_name, 'CPU', 24) as avg_cpu_24h,
    get_avg_metric_value(server_name, 'MEMORY', 24) as avg_memory_24h
FROM performance_metrics
ORDER BY 
    CASE get_server_health_status(server_name)
        WHEN 'CRITICAL' THEN 1
        WHEN 'DEGRADED' THEN 2  
        WHEN 'WARNING' THEN 3
        ELSE 4
    END;

-- **TAKE SCREENSHOT 8: After testing alerts - Show trigger alerts and health status**

-- ====================================================================
-- STEP 8: VIEW CURRENT METRICS AND ALERTS
-- ====================================================================

-- View recent performance metrics
SELECT 
    server_name,
    metric_type,
    metric_value,
    threshold_limit,
    status,
    TO_CHAR(recorded_at, 'DD-MON HH24:MI:SS') as recorded_time
FROM performance_metrics 
ORDER BY recorded_at DESC;

-- View all alerts generated
SELECT 
    server_name,
    alert_level,
    metric_type,
    metric_value,
    alert_message,
    TO_CHAR(created_at, 'DD-MON HH24:MI:SS') as alert_time
FROM server_alerts 
ORDER BY created_at DESC;

-- Summary statistics
SELECT 
    'Total Metrics Logged' as metric, COUNT(*) as value FROM performance_metrics
UNION ALL
SELECT 
    'Total Alerts Generated' as metric, COUNT(*) as value FROM server_alerts
UNION ALL  
SELECT 
    'Critical Alerts' as metric, COUNT(*) as value FROM server_alerts WHERE alert_level = 'CRITICAL'
UNION ALL
SELECT 
    'Warning Alerts' as metric, COUNT(*) as value FROM server_alerts WHERE alert_level = 'WARNING';

-- ====================================================================
-- ADDITIONAL DEMO: Test Alert System
-- ====================================================================

-- Test the alert system with extreme values
BEGIN
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('🧪 TESTING ALERT SYSTEM WITH EXTREME VALUES:');
    DBMS_OUTPUT.PUT_LINE('');
    
    -- This should trigger critical alerts
    log_server_metrics('PROD-SERVER-01', 'CPU', 98.7, 80);
    log_server_metrics('PROD-SERVER-01', 'MEMORY', 99.2, 85);
    log_server_metrics('PROD-SERVER-02', 'DISK', 97.5, 90);
END;
/